[build]
command = "npm run build"
publish = "dist"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Opener-Policy = "same-origin"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true